// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdjnvcuzvbkzvagwaurp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkam52Y3V6dmJrenZhZ3dhdXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTAwNDgsImV4cCI6MjA3MjcyNjA0OH0.yeA73X6ZuFet20JFwAgiBTPsrISQ4-raFjkL68BzSus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});